In [31]:
import napari
from skimage import data
import pandas as pd
import numpy as np
image = data.hubble_deep_field()
save_dir = '/Users/aimachine/Downloads/'

In [54]:

viewer = napari.Viewer()
viewer.add_image(image)
Landmarks = 'Landmarks'

# add the first points layer for BestZCadherine Z point
viewer.add_shapes(name= Landmarks, shape_type = 'line', face_color = [0]*4, edge_color = "red", edge_width = 1, ndim = 3)
viewer.layers[Landmarks].mode = 'add_line'
viewer.show(block=True)
       
        
Landmarksdata = viewer.layers[Landmarks].data
Landmarksdatalist = []
for data in Landmarksdata:
    
    Landmarksdatalist.append(data.tolist())
    
row_lengths = []

for row in Landmarksdatalist:
   
    row_lengths.append(len(row))

max_length = max(row_lengths)

for row in Landmarksdatalist:

    while len(row) < max_length:
        row.append([None, None, None])

Landmarksdata = np.array(Landmarksdatalist)


number_lines = Landmarksdata.shape[0]
line_index = np.arange(0, number_lines, 1)
df = [pd.DataFrame(Landmarksdata[i,:], columns = ['L','Y','X']) for i in range(0,number_lines)]
Landmarksdf = pd.concat(df, keys = line_index)

Landmarksdf.to_csv(save_dir + '/' + 'ONEAT' + Landmarks + 'Test' +  '.csv')

/Users/aimachine/opt/anaconda3/envs/testenv/lib/python3.9/site-packages/napari/_vispy/vispy_camera.py:109: RuntimeWarning: divide by zero encountered in true_divide
  zoom = np.min(canvas_size / scale)


[[[0.0 116.15050072040248 276.08411255409925]
  [0.0 194.70017349219745 337.8936911286265]
  [0.0 391.7182051985029 493.7053371185804]
  [0.0 538.5159543130048 612.1736960530909]]

 [[0.0 215.30336635037318 108.68317058142145]
  [0.0 682.7383043202351 446.06045363404905]
  [0 None None]
  [0 None None]]]
       L           Y           X
0 0  0.0  116.150501  276.084113
  1  0.0  194.700173  337.893691
  2  0.0  391.718205  493.705337
  3  0.0  538.515954  612.173696
1 0  0.0  215.303366  108.683171
  1  0.0  682.738304  446.060454
  2    0        None        None
  3    0        None        None
